language: go

go:
  - 1.16

install:
  # Prevent default install task that does a `go get -t ./...`
  - true

before_install:
  - go install github.com/onsi/ginkgo/ginkgo@07d85e6b10c4289c7d612f9b13f45ba36f66d55b

script:
  - make test
