// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	sync "sync"

	metrics "github.com/alphagov/paas-metric-exporter/metrics"
)

type FakeSender struct {
	AppCreatedStub        func(string) error
	appCreatedMutex       sync.RWMutex
	appCreatedArgsForCall []struct {
		arg1 string
	}
	appCreatedReturns struct {
		result1 error
	}
	appCreatedReturnsOnCall map[int]struct {
		result1 error
	}
	AppDeletedStub        func(string) error
	appDeletedMutex       sync.RWMutex
	appDeletedArgsForCall []struct {
		arg1 string
	}
	appDeletedReturns struct {
		result1 error
	}
	appDeletedReturnsOnCall map[int]struct {
		result1 error
	}
	GaugeStub        func(metrics.GaugeMetric) error
	gaugeMutex       sync.RWMutex
	gaugeArgsForCall []struct {
		arg1 metrics.GaugeMetric
	}
	gaugeReturns struct {
		result1 error
	}
	gaugeReturnsOnCall map[int]struct {
		result1 error
	}
	IncrStub        func(metrics.CounterMetric) error
	incrMutex       sync.RWMutex
	incrArgsForCall []struct {
		arg1 metrics.CounterMetric
	}
	incrReturns struct {
		result1 error
	}
	incrReturnsOnCall map[int]struct {
		result1 error
	}
	PrecisionTimingStub        func(metrics.PrecisionTimingMetric) error
	precisionTimingMutex       sync.RWMutex
	precisionTimingArgsForCall []struct {
		arg1 metrics.PrecisionTimingMetric
	}
	precisionTimingReturns struct {
		result1 error
	}
	precisionTimingReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSender) AppCreated(arg1 string) error {
	fake.appCreatedMutex.Lock()
	ret, specificReturn := fake.appCreatedReturnsOnCall[len(fake.appCreatedArgsForCall)]
	fake.appCreatedArgsForCall = append(fake.appCreatedArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("AppCreated", []interface{}{arg1})
	fake.appCreatedMutex.Unlock()
	if fake.AppCreatedStub != nil {
		return fake.AppCreatedStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.appCreatedReturns
	return fakeReturns.result1
}

func (fake *FakeSender) AppCreatedCallCount() int {
	fake.appCreatedMutex.RLock()
	defer fake.appCreatedMutex.RUnlock()
	return len(fake.appCreatedArgsForCall)
}

func (fake *FakeSender) AppCreatedCalls(stub func(string) error) {
	fake.appCreatedMutex.Lock()
	defer fake.appCreatedMutex.Unlock()
	fake.AppCreatedStub = stub
}

func (fake *FakeSender) AppCreatedArgsForCall(i int) string {
	fake.appCreatedMutex.RLock()
	defer fake.appCreatedMutex.RUnlock()
	argsForCall := fake.appCreatedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeSender) AppCreatedReturns(result1 error) {
	fake.appCreatedMutex.Lock()
	defer fake.appCreatedMutex.Unlock()
	fake.AppCreatedStub = nil
	fake.appCreatedReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSender) AppCreatedReturnsOnCall(i int, result1 error) {
	fake.appCreatedMutex.Lock()
	defer fake.appCreatedMutex.Unlock()
	fake.AppCreatedStub = nil
	if fake.appCreatedReturnsOnCall == nil {
		fake.appCreatedReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.appCreatedReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSender) AppDeleted(arg1 string) error {
	fake.appDeletedMutex.Lock()
	ret, specificReturn := fake.appDeletedReturnsOnCall[len(fake.appDeletedArgsForCall)]
	fake.appDeletedArgsForCall = append(fake.appDeletedArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("AppDeleted", []interface{}{arg1})
	fake.appDeletedMutex.Unlock()
	if fake.AppDeletedStub != nil {
		return fake.AppDeletedStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.appDeletedReturns
	return fakeReturns.result1
}

func (fake *FakeSender) AppDeletedCallCount() int {
	fake.appDeletedMutex.RLock()
	defer fake.appDeletedMutex.RUnlock()
	return len(fake.appDeletedArgsForCall)
}

func (fake *FakeSender) AppDeletedCalls(stub func(string) error) {
	fake.appDeletedMutex.Lock()
	defer fake.appDeletedMutex.Unlock()
	fake.AppDeletedStub = stub
}

func (fake *FakeSender) AppDeletedArgsForCall(i int) string {
	fake.appDeletedMutex.RLock()
	defer fake.appDeletedMutex.RUnlock()
	argsForCall := fake.appDeletedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeSender) AppDeletedReturns(result1 error) {
	fake.appDeletedMutex.Lock()
	defer fake.appDeletedMutex.Unlock()
	fake.AppDeletedStub = nil
	fake.appDeletedReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSender) AppDeletedReturnsOnCall(i int, result1 error) {
	fake.appDeletedMutex.Lock()
	defer fake.appDeletedMutex.Unlock()
	fake.AppDeletedStub = nil
	if fake.appDeletedReturnsOnCall == nil {
		fake.appDeletedReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.appDeletedReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSender) Gauge(arg1 metrics.GaugeMetric) error {
	fake.gaugeMutex.Lock()
	ret, specificReturn := fake.gaugeReturnsOnCall[len(fake.gaugeArgsForCall)]
	fake.gaugeArgsForCall = append(fake.gaugeArgsForCall, struct {
		arg1 metrics.GaugeMetric
	}{arg1})
	fake.recordInvocation("Gauge", []interface{}{arg1})
	fake.gaugeMutex.Unlock()
	if fake.GaugeStub != nil {
		return fake.GaugeStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.gaugeReturns
	return fakeReturns.result1
}

func (fake *FakeSender) GaugeCallCount() int {
	fake.gaugeMutex.RLock()
	defer fake.gaugeMutex.RUnlock()
	return len(fake.gaugeArgsForCall)
}

func (fake *FakeSender) GaugeCalls(stub func(metrics.GaugeMetric) error) {
	fake.gaugeMutex.Lock()
	defer fake.gaugeMutex.Unlock()
	fake.GaugeStub = stub
}

func (fake *FakeSender) GaugeArgsForCall(i int) metrics.GaugeMetric {
	fake.gaugeMutex.RLock()
	defer fake.gaugeMutex.RUnlock()
	argsForCall := fake.gaugeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeSender) GaugeReturns(result1 error) {
	fake.gaugeMutex.Lock()
	defer fake.gaugeMutex.Unlock()
	fake.GaugeStub = nil
	fake.gaugeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSender) GaugeReturnsOnCall(i int, result1 error) {
	fake.gaugeMutex.Lock()
	defer fake.gaugeMutex.Unlock()
	fake.GaugeStub = nil
	if fake.gaugeReturnsOnCall == nil {
		fake.gaugeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.gaugeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSender) Incr(arg1 metrics.CounterMetric) error {
	fake.incrMutex.Lock()
	ret, specificReturn := fake.incrReturnsOnCall[len(fake.incrArgsForCall)]
	fake.incrArgsForCall = append(fake.incrArgsForCall, struct {
		arg1 metrics.CounterMetric
	}{arg1})
	fake.recordInvocation("Incr", []interface{}{arg1})
	fake.incrMutex.Unlock()
	if fake.IncrStub != nil {
		return fake.IncrStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.incrReturns
	return fakeReturns.result1
}

func (fake *FakeSender) IncrCallCount() int {
	fake.incrMutex.RLock()
	defer fake.incrMutex.RUnlock()
	return len(fake.incrArgsForCall)
}

func (fake *FakeSender) IncrCalls(stub func(metrics.CounterMetric) error) {
	fake.incrMutex.Lock()
	defer fake.incrMutex.Unlock()
	fake.IncrStub = stub
}

func (fake *FakeSender) IncrArgsForCall(i int) metrics.CounterMetric {
	fake.incrMutex.RLock()
	defer fake.incrMutex.RUnlock()
	argsForCall := fake.incrArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeSender) IncrReturns(result1 error) {
	fake.incrMutex.Lock()
	defer fake.incrMutex.Unlock()
	fake.IncrStub = nil
	fake.incrReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSender) IncrReturnsOnCall(i int, result1 error) {
	fake.incrMutex.Lock()
	defer fake.incrMutex.Unlock()
	fake.IncrStub = nil
	if fake.incrReturnsOnCall == nil {
		fake.incrReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.incrReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSender) PrecisionTiming(arg1 metrics.PrecisionTimingMetric) error {
	fake.precisionTimingMutex.Lock()
	ret, specificReturn := fake.precisionTimingReturnsOnCall[len(fake.precisionTimingArgsForCall)]
	fake.precisionTimingArgsForCall = append(fake.precisionTimingArgsForCall, struct {
		arg1 metrics.PrecisionTimingMetric
	}{arg1})
	fake.recordInvocation("PrecisionTiming", []interface{}{arg1})
	fake.precisionTimingMutex.Unlock()
	if fake.PrecisionTimingStub != nil {
		return fake.PrecisionTimingStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.precisionTimingReturns
	return fakeReturns.result1
}

func (fake *FakeSender) PrecisionTimingCallCount() int {
	fake.precisionTimingMutex.RLock()
	defer fake.precisionTimingMutex.RUnlock()
	return len(fake.precisionTimingArgsForCall)
}

func (fake *FakeSender) PrecisionTimingCalls(stub func(metrics.PrecisionTimingMetric) error) {
	fake.precisionTimingMutex.Lock()
	defer fake.precisionTimingMutex.Unlock()
	fake.PrecisionTimingStub = stub
}

func (fake *FakeSender) PrecisionTimingArgsForCall(i int) metrics.PrecisionTimingMetric {
	fake.precisionTimingMutex.RLock()
	defer fake.precisionTimingMutex.RUnlock()
	argsForCall := fake.precisionTimingArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeSender) PrecisionTimingReturns(result1 error) {
	fake.precisionTimingMutex.Lock()
	defer fake.precisionTimingMutex.Unlock()
	fake.PrecisionTimingStub = nil
	fake.precisionTimingReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSender) PrecisionTimingReturnsOnCall(i int, result1 error) {
	fake.precisionTimingMutex.Lock()
	defer fake.precisionTimingMutex.Unlock()
	fake.PrecisionTimingStub = nil
	if fake.precisionTimingReturnsOnCall == nil {
		fake.precisionTimingReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.precisionTimingReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSender) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.appCreatedMutex.RLock()
	defer fake.appCreatedMutex.RUnlock()
	fake.appDeletedMutex.RLock()
	defer fake.appDeletedMutex.RUnlock()
	fake.gaugeMutex.RLock()
	defer fake.gaugeMutex.RUnlock()
	fake.incrMutex.RLock()
	defer fake.incrMutex.RUnlock()
	fake.precisionTimingMutex.RLock()
	defer fake.precisionTimingMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSender) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ metrics.Sender = new(FakeSender)
